version: '3.8'
services:
    db:
        container_name: postgresql-databse
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        volumes:
            - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

    backend-server:
        container_name: backend-server
        build: .
        depends_on:
            - db
        ports:
            - 8080:8080
