version: '3.8'
services:
    db:
        container_name: postgresql-db-container
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        # volumes:
        #     - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    backend-server:
        container_name: backend-server
        build: .
        depends_on:
            - db
        environment:
            - DB_HOST=postgresql-db-container
            - DB_PORT=5432
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PASSWORD=root
        ports:
            - 8080:8080
